apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: cloudapp
type: Opaque
stringData:
  DB_PASSWORD: "CloudApp2024Secure"
  JWT_SECRET: "cloudapp-jwt-super-secret-key-2024-minimum-32-chars"