apiVersion: v1
kind: LimitRange
metadata:
  name: cloudapp-limits
  namespace: cloudapp
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: "1"
      memory: 512Mi
    min:
      cpu: 10m
      memory: 16Mi
  - type: Pod
    max:
      cpu: "2"
      memory: 1Gi
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi
      