apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudapp-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jithu-cell/eks-3tier-project.git
    targetRevision: main
    path: kubernetes/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true